var balsas_gtx = [
  {
    "Espesor":"1",
    "Altura":"[0..10)",
    "Dmax":"[0..60)",
    "RT":15,
    "ELONG":50,
    "RCBR":2700,
    "RPERF_CONO":"<20",
    "AB_PORO":"<70",
    "KVERT":6,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"1",
    "Altura":"[0..10)",
    "Dmax":"[60..120)",
    "RT":18,
    "ELONG":50,
    "RCBR":3000,
    "RPERF_CONO":"<15",
    "AB_PORO":"<60",
    "KVERT":7,
    "GEOTESAN":"NT-25"
  },
  {
    "Espesor":"1",
    "Altura":"[0..10)",
    "Dmax":"[120..∞)",
    "RT":21,
    "ELONG":50,
    "RCBR":3700,
    "RPERF_CONO":"<10",
    "AB_PORO":"<60",
    "KVERT":7,
    "GEOTESAN":"NT-35"
  },
  {
    "Espesor":"1",
    "Altura":"[10..∞)",
    "Dmax":"[0..60)",
    "RT":18,
    "ELONG":50,
    "RCBR":3000,
    "RPERF_CONO":"<15",
    "AB_PORO":"<60",
    "KVERT":7,
    "GEOTESAN":"NT-25"
  },
  {
    "Espesor":"1",
    "Altura":"[10..∞)",
    "Dmax":"[60..120)",
    "RT":21,
    "ELONG":50,
    "RCBR":3700,
    "RPERF_CONO":"<10",
    "AB_PORO":"<60",
    "KVERT":7,
    "GEOTESAN":"NT-35"
  },
  {
    "Espesor":"1",
    "Altura":"[10..∞)",
    "Dmax":"[120..∞)",
    "RT":25,
    "ELONG":50,
    "RCBR":4400,
    "RPERF_CONO":"<10",
    "AB_PORO":"<60",
    "KVERT":7,
    "GEOTESAN":"NT-40"
  },
  {
    "Espesor":"1,5",
    "Altura":"[0..10)",
    "Dmax":"[0..60)",
    "RT":15,
    "ELONG":50,
    "RCBR":2700,
    "RPERF_CONO":"<20",
    "AB_PORO":"<70",
    "KVERT":7,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"1,5",
    "Altura":"[0..10)",
    "Dmax":"[60..120)",
    "RT":15,
    "ELONG":50,
    "RCBR":2700,
    "RPERF_CONO":"<20",
    "AB_PORO":"<70",
    "KVERT":6,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"1,5",
    "Altura":"[0..10)",
    "Dmax":"[120..∞)",
    "RT":18,
    "ELONG":50,
    "RCBR":3000,
    "RPERF_CONO":"<15",
    "AB_PORO":"<60",
    "KVERT":7,
    "GEOTESAN":"NT-25"
  },
  {
    "Espesor":"1,5",
    "Altura":"[10..∞)",
    "Dmax":"[0..60)",
    "RT":15,
    "ELONG":50,
    "RCBR":2700,
    "RPERF_CONO":"<20",
    "AB_PORO":"<70",
    "KVERT":6,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"1,5",
    "Altura":"[10..∞)",
    "Dmax":"[60..120)",
    "RT":18,
    "ELONG":50,
    "RCBR":3000,
    "RPERF_CONO":"<15",
    "AB_PORO":"<60",
    "KVERT":7,
    "GEOTESAN":"NT-25"
  },
  {
    "Espesor":"1,5",
    "Altura":"[10..∞)",
    "Dmax":"[120..∞)",
    "RT":21,
    "ELONG":50,
    "RCBR":3700,
    "RPERF_CONO":"<10",
    "AB_PORO":"<60",
    "KVERT":7,
    "GEOTESAN":"NT-35"
  },
  {
    "Espesor":"2",
    "Altura":"[0..10)",
    "Dmax":"[0..60)",
    "RT":12,
    "ELONG":50,
    "RCBR":2200,
    "RPERF_CONO":"<25",
    "AB_PORO":"<70",
    "KVERT":6,
    "GEOTESAN":"NT-21"
  },
  {
    "Espesor":"2",
    "Altura":"[0..10)",
    "Dmax":"[60..120)",
    "RT":15,
    "ELONG":50,
    "RCBR":2700,
    "RPERF_CONO":"<20",
    "AB_PORO":"<70",
    "KVERT":6,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"2",
    "Altura":"[0..10)",
    "Dmax":"[120..∞)",
    "RT":15,
    "ELONG":50,
    "RCBR":2700,
    "RPERF_CONO":"<20",
    "AB_PORO":"<70",
    "KVERT":7,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"2",
    "Altura":"[10..∞)",
    "Dmax":"[0..60)",
    "RT":15,
    "ELONG":50,
    "RCBR":2700,
    "RPERF_CONO":"<20",
    "AB_PORO":"<70",
    "KVERT":6,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"2",
    "Altura":"[10..∞)",
    "Dmax":"[60..120)",
    "RT":15,
    "ELONG":50,
    "RCBR":2700,
    "RPERF_CONO":"<12",
    "AB_PORO":"<70",
    "KVERT":7,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"2",
    "Altura":"[10..∞)",
    "Dmax":"[120..∞)",
    "RT":18,
    "ELONG":50,
    "RCBR":3000,
    "RPERF_CONO":"<15",
    "AB_PORO":"<60",
    "KVERT":7,
    "GEOTESAN":"NT-25"
  }
];

var balsas_gtxtl = [
  {
    "Espesor":"1",
    "Altura":"[0..10)",
    "Dmax":"[0..60)",
    "RT":16,
    "ELONG":"55,76",
    "RCBR":"2,7",
    "RPERF_CONO":"18,65",
    "AB_PORO":"0,06",
    "KVERT":79,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"1",
    "Altura":"[0..10)",
    "Dmax":"[60..120)",
    "RT":20,
    "ELONG":"60",
    "RCBR":"3,25",
    "RPERF_CONO":"15,35",
    "AB_PORO":"0,059",
    "KVERT":74,
    "GEOTESAN":"NT-25"
  },
  {
    "Espesor":"1",
    "Altura":"[0..10)",
    "Dmax":"[120..∞)",
    "RT":23,
    "ELONG":"57,91",
    "RCBR":"4",
    "RPERF_CONO":"9,8",
    "AB_PORO":"0,058",
    "KVERT":63,
    "GEOTESAN":"NT-35"
  },
  {
    "Espesor":"1",
    "Altura":"[10..∞)",
    "Dmax":"[0..60)",
    "RT":20,
    "ELONG":"60",
    "RCBR":"3,25",
    "RPERF_CONO":"15,35",
    "AB_PORO":"0,059",
    "KVERT":74,
    "GEOTESAN":"NT-25"
  },
  {
    "Espesor":"1",
    "Altura":"[10..∞)",
    "Dmax":"[60..120)",
    "RT":23,
    "ELONG":"57,91",
    "RCBR":"4",
    "RPERF_CONO":"9,8",
    "AB_PORO":"0,058",
    "KVERT":63,
    "GEOTESAN":"NT-35"
  },
  {
    "Espesor":"1",
    "Altura":"[10..∞)",
    "Dmax":"[120..∞)",
    "RT":26,
    "ELONG":"60",
    "RCBR":"4,49",
    "RPERF_CONO":"9,6",
    "AB_PORO":"0,057",
    "KVERT":50,
    "GEOTESAN":"NT-40"
  },
  {
    "Espesor":"1,5",
    "Altura":"[0..10)",
    "Dmax":"[0..60)",
    "RT":16,
    "ELONG":"55,76",
    "RCBR":"2,7",
    "RPERF_CONO":"18,65",
    "AB_PORO":"0,06",
    "KVERT":79,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"1,5",
    "Altura":"[0..10)",
    "Dmax":"[60..120)",
    "RT":16,
    "ELONG":"55,76",
    "RCBR":"2,7",
    "RPERF_CONO":"18,65",
    "AB_PORO":"0,06",
    "KVERT":79,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"1,5",
    "Altura":"[0..10)",
    "Dmax":"[120..∞)",
    "RT":20,
    "ELONG":"60",
    "RCBR":"3,25",
    "RPERF_CONO":"15,35",
    "AB_PORO":"0,059",
    "KVERT":74,
    "GEOTESAN":"NT-25"
  },
  {
    "Espesor":"1,5",
    "Altura":"[10..∞)",
    "Dmax":"[0..60)",
    "RT":16,
    "ELONG":"55,76",
    "RCBR":"2,7",
    "RPERF_CONO":"18,65",
    "AB_PORO":"0,06",
    "KVERT":79,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"1,5",
    "Altura":"[10..∞)",
    "Dmax":"[60..120)",
    "RT":20,
    "ELONG":"60",
    "RCBR":"3,25",
    "RPERF_CONO":"15,35",
    "AB_PORO":"0,059",
    "KVERT":74,
    "GEOTESAN":"NT-25"
  },
  {
    "Espesor":"1,5",
    "Altura":"[10..∞)",
    "Dmax":"[120..∞)",
    "RT":23,
    "ELONG":"57,91",
    "RCBR":"4",
    "RPERF_CONO":"9,8",
    "AB_PORO":"0,058",
    "KVERT":63,
    "GEOTESAN":"NT-35"
  },
  {
    "Espesor":"2",
    "Altura":"[0..10)",
    "Dmax":"[0..60)",
    "RT":14,
    "ELONG":"54,83",
    "RCBR":"2,26",
    "RPERF_CONO":"20,75",
    "AB_PORO":"0,06",
    "KVERT":85,
    "GEOTESAN":"NT-21"
  },
  {
    "Espesor":"2",
    "Altura":"[0..10)",
    "Dmax":"[60..120)",
    "RT":16,
    "ELONG":"55,76",
    "RCBR":"2,7",
    "RPERF_CONO":"18,65",
    "AB_PORO":"0,06",
    "KVERT":79,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"2",
    "Altura":"[0..10)",
    "Dmax":"[120..∞)",
    "RT":16,
    "ELONG":"55,76",
    "RCBR":"2,7",
    "RPERF_CONO":"18,65",
    "AB_PORO":"0,06",
    "KVERT":79,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"2",
    "Altura":"[10..∞)",
    "Dmax":"[0..60)",
    "RT":16,
    "ELONG":"55,76",
    "RCBR":"2,7",
    "RPERF_CONO":"18,65",
    "AB_PORO":"0,06",
    "KVERT":79,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"2",
    "Altura":"[10..∞)",
    "Dmax":"[60..120)",
    "RT":16,
    "ELONG":"55,76",
    "RCBR":"2,7",
    "RPERF_CONO":"18,65",
    "AB_PORO":"0,06",
    "KVERT":79,
    "GEOTESAN":"NT-23"
  },
  {
    "Espesor":"2",
    "Altura":"[10..∞)",
    "Dmax":"[120..∞)",
    "RT":20,
    "ELONG":"60",
    "RCBR":"3,25",
    "RPERF_CONO":"15,35",
    "AB_PORO":"0,059",
    "KVERT":74,
    "GEOTESAN":"NT-25"
  }
];

function calcula() {
	//Inputs
	var ih = $('#i-h').val();
	var e = $('#i-e').val();
	var id = $('#i-d').val();
	if (ih.length === 0 || id === 0 ) {
		alert("Debe introducir todos los valores del formulario");
		return false;
	}
	
  if (isNaN(id) || isNaN(ih)) {
    alert("Los valores deben ser numéricos");
    return false;
  }
	//Storage interval from the input
	var h;
	var d;

	if (ih < 0) {
    alert("La altura debe ser manor que 0");
    return false;
  } else if (ih < 10) {
		h = '[0..10)'
	} else if (ih >= 10 ) {
		h = "[10..∞)";
	}

	if (id < 0) {
		alert ("El valor de D debe ser mayor que 0");
		return false;
	} else if (id >= 0 && id < 60) {
		d = "[0..60)";
	} else if (id >= 60 && id < 120) {
		d = "[60..120)";
	} else if (id >= 120) {
		d = '[120..∞)'
	}

  var result = false;
	$.each(balsas_gtx, function(i, item) {
		if (balsas_gtx[i]['Altura'] == h ) {
			if (balsas_gtx[i]['Espesor'] == e) {
				if (balsas_gtx[i]['Dmax'] == d) {
					//Relleno valores del formulario y salgo de la iteración
					$('#rt-geotexan-value').val(balsas_gtx[i]['RT']);
					$('#elong-geotexan-value').val(balsas_gtx[i]['ELONG']);
					$('#cbr-geotexan-value').val(balsas_gtx[i]['RCBR']);
					$('#perfcono-geotexan-value').val(balsas_gtx[i]['RPERF_CONO']);
					$('#kplano-geotexan-value').val(balsas_gtx[i]['KVERT']);
					$('#abcono-geotexan-value').val(balsas_gtx[i]['AB_PORO']);
					$('#rt-geotextil-value').val(balsas_gtxtl[i]['RT']);
					$('#elong-geotextil-value').val(balsas_gtxtl[i]['ELONG']);
					$('#cbr-geotextil-value').val(balsas_gtxtl[i]['RCBR']);
					$('#perfcono-geotextil-value').val(balsas_gtxtl[i]['RPERF_CONO']);
					$('#kplano-geotextil-value').val(balsas_gtxtl[i]['KVERT']);
					$('#abcono-geotextil-value').val(balsas_gtxtl[i]['AB_PORO']);
					$('#product').val(balsas_gtxtl[i]['GEOTESAN']);
                    result = true;
					return true;
				}
			}
		}
	});
  if (!result) {
      alert('No se han encontrado resultados');
  }
}